### ISSUE TITLE
[RDD.lookup] how to get the value by a given key?

### ISSUE THREAD

**Issue by xjlin0** [ondra-m/ruby-spark#12]
First, this work is wonderful, your work is absolutely amazing!

If I want to lookup a certain pair by given key, what method could I use? If there's not, in which file I can write one?  Thanks!

https://spark.apache.org/docs/latest/api/python/pyspark.html?highlight=sort#pyspark.RDD.lookup

**Comment by ondra-m** [comment]
Thanks. RDD now have method `lookup`. Please try it.

**Comment by xjlin0** [comment]
great!  thanks!
