### ISSUE TITLE
toy input works but fail on bigger inputs

### ISSUE THREAD

**Issue by xjlin0** [ondra-m/ruby-spark#14]
Hi Ondra:

Really appreciate of writing such a great gem and I'm using it to suggest "friends you may know" function like facebook.  Ruby-spark works for toy input but failed on the bigger input. Also it report error if I use RDD.take(2) even with toy input. Do you have a guess where should I look? Thanks!

====
Logic: each line represents a userID and the user's friends IDs.  For each line, make all these friends share the leading user as the common friend. Remove those pair who's already friends. Aggregate and suggest users with most common friends.

Input:  UserID <tab> FriendID, FriendID, FriendID....
Output: UserID, [[suggestedID, commonFriendCount], [suggestedID, commonFriendCount], [suggestedID, commonFriendCount] .....  ]

toy input: https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1testdata.txt
bigger input: http://snap.stanford.edu/class/cs246-data/hw1q1.zip

Working PySpark code, (works in PySpark shell, by typing execfile('q1_people_you_may_know_spark.py') ):
https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1_people_you_may_know_spark.py

My Ruby-Spark code, run in the ruby-spark shell  (by typing load('q1_people_you_may_know_spark.rb') ) , works for toy input but failed for bigger input.
https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1_people_you_may_know_spark.rb

Thanks!

**Comment by ondra-m** [comment]
Links go to 404:

https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1_people_you_may_know.py
https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1_people_you_may_know.rb

**Comment by xjlin0** [comment]
https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1_people_you_may_know_spark.py
https://github.com/xjlin0/cs246/blob/master/w2015/hw1/q1_people_you_may_know_spark.rb

fixed, thanks a lot!
