### ISSUE TITLE
Ruby-spark shell: No FileSystem for scheme: file

### ISSUE THREAD

**Issue by yduf** [ondra-m/ruby-spark#15]
I am trying Ruby-spark and I have sucessfully installed ruby-spark on a linux mint os
(yet there is an issue with the sbt/sbt script that faild to detect when the download fail => I ended up with a jar corresponding to the page html 404)

I have successfully run the PI test on the local cluster using ruby-spark shell,
I cannot use local file as input for RDD like this:
expo = Spark.sc.text_file("/home/yves/test.csv")
expo.collect

 I keep having:
Spark::RDDError: java.io.IOException: No FileSystem for scheme: file
from /home/yves/.rvm/gems/ruby-2.2.1/gems/ruby-spark-1.2.0/lib/spark/rdd.rb:207:in `rescue in collect'

I don't know what to fix in the sbt build script.  But it is really linked to what is being put into
ruby-spark-deps.jar, Because replacing that file with a already build spark.jar make it works.

From what I have read it seems to be a packaging/build issue with hadoop
(see http://stackoverflow.com/questions/17265002/hadoop-no-filesystem-for-scheme-file)

Updating that issue: I understand that it certainly more a spark issue than a Ruby-spark issue,
but as ruby-spark self deliver spark, it would be nice to have a fully working spark version available,
or have pointer to fix it.

**Comment by ondra-m** [comment]
Please try rebuild command with `--hadoop-version 2.4.0`
